#!/usr/bin/env python
# -*- coding: UTF-8 -*-

import click
import click_completion

click_completion.init()
targetShell = 'fish'

@click.group()
def completion():
    pass


@completion.command()
@click.argument("program", type=click.STRING, required=True)
def show(program):
    """
    显示fish的补全代码
    """
    print(click_completion.get_code(targetShell, program))


@completion.command()
@click.argument("program", type=click.STRING, required=True)
def install(program):
    """
    安装fish的补全代码到fish指定目录
    """
    click_completion.install(targetShell, program)


completion()
